import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

import type { Category, TreeIndex } from "./engineTree";

/*
  Build-time read of engine/tree/. Same job as mathsTree.ts: Node runs this from Astro
  frontmatter during SSG, never in the browser — hence the `.server` suffix, and hence the
  types living apart in engineTree.ts, which the island does import.

  The JSON is generated by `ms-cli tree` out of engine/docs/ and engine/corpus/. Nothing
  here decides what is covered: a capability cannot be shown as done without a corpus case
  behind it, because nothing in this layer can write a check.
*/

const TREE_DIR = resolve(process.cwd(), "engine/tree");

function read<T>(file: string): T {
  return JSON.parse(readFileSync(join(TREE_DIR, file), "utf8")) as T;
}

/** The index: totals plus one row per category, in inventory order. */
export function readIndex(): TreeIndex {
  return read<TreeIndex>("index.json");
}

/** One category with its whole tree. Throws if the slug has no file — a broken route. */
export function readCategory(slug: string): Category {
  return read<Category>(`${slug}.json`);
}
