import { useState } from "react";

import KatexMath from "@/components/artifacts/KatexMath";
import FactList from "@/components/engine-tree/FactList";
import { solve } from "@/lib/engine/runner";
import type { ResultDoc } from "@/lib/engine/types";
import { decimalOf, toSteps, verificationLabel } from "@/lib/engine/represent/toSteps";
import { isLeaf, type CapabilityCase, type CapabilityNode } from "@/lib/engineTree";

/*
  The capability tree of one category, with its cases runnable against the real engine.

  Two things this is not. It is not a checklist someone maintains: every check comes from
  engine/tree/*.json, generated by `ms-cli tree` out of docs/ + corpus/. And it is not a
  screenshot of a test run: pressing "run" loads the WASM and solves, then compares against
  what the corpus says. `pnpm engine:browser` made watchable.
*/

export type TreeStrings = {
  case: string;
  cases: string;
  noCases: string;
  run: string;
  running: string;
  matches: string;
  mismatch: string;
  expected: string;
  got: string;
};

export default function CapabilityTree({
  nodes,
  strings,
}: {
  nodes: CapabilityNode[];
  strings: TreeStrings;
}) {
  return (
    <div className="space-y-3">
      {nodes.map((node) => (
        <Node key={node.title} node={node} strings={strings} depth={0} />
      ))}
    </div>
  );
}

function Node({
  node,
  strings,
  depth,
}: {
  node: CapabilityNode;
  strings: TreeStrings;
  depth: number;
}) {
  if (isLeaf(node)) return <Leaf leaf={node} strings={strings} />;

  /* Sections open by default only while they are small: Common Core has branches of
     hundreds of leaves, and a page that opens them all at once is unreadable. */
  const [open, setOpen] = useState(node.leaves <= 40);

  return (
    <section className={depth === 0 ? "rounded-[var(--radius-md)] border border-border bg-surface" : ""}>
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className={`flex w-full items-baseline justify-between gap-3 text-left ${
          depth === 0 ? "px-5 py-3" : "py-2"
        }`}
        aria-expanded={open}
      >
        <span className="flex items-baseline gap-2">
          <Mark checked={node.checked} />
          <span className={depth === 0 ? "font-semibold text-ink" : "text-sm text-ink"}>
            {node.title}
          </span>
        </span>
        <span className="font-mono text-[11px] text-ink-muted">
          {node.covered}/{node.leaves}
        </span>
      </button>

      {open && (
        <div className={depth === 0 ? "border-t border-border px-5 py-2" : "border-l border-border pl-4"}>
          {node.children.map((child) => (
            <Node key={child.title} node={child} strings={strings} depth={depth + 1} />
          ))}
        </div>
      )}
    </section>
  );
}

function Leaf({ leaf, strings }: { leaf: { title: string; cases: CapabilityCase[]; checked: boolean }; strings: TreeStrings }) {
  const [open, setOpen] = useState(false);
  const empty = leaf.cases.length === 0;

  return (
    <div className="py-1">
      <button
        type="button"
        onClick={() => !empty && setOpen(!open)}
        disabled={empty}
        aria-expanded={empty ? undefined : open}
        className={`flex w-full items-baseline justify-between gap-3 text-left text-sm ${
          empty ? "cursor-default text-ink-muted/60" : "text-ink hover:text-primary"
        }`}
      >
        <span className="flex items-baseline gap-2">
          <Mark checked={leaf.checked} />
          <span>{leaf.title}</span>
        </span>
        <span className="shrink-0 font-mono text-[11px] text-ink-muted">
          {empty
            ? strings.noCases
            : `${leaf.cases.length} ${leaf.cases.length === 1 ? strings.case : strings.cases}`}
        </span>
      </button>

      {open && (
        <div className="mt-2 space-y-2 border-l border-border pl-4">
          {leaf.cases.map((corpusCase) => (
            <Case key={corpusCase.name} corpusCase={corpusCase} strings={strings} />
          ))}
        </div>
      )}
    </div>
  );
}

/* `expected` y `got` viajan sueltos y no como una cadena ya montada: quien lee un fallo
   necesita ver las dos cosas etiquetadas, no una flecha entre dos LaTeX. */
type Outcome = {
  agrees: boolean;
  expected: string;
  got: string;
  /*
    Whether expected/got hold LaTeX or a plain error kind. Carried explicitly
    rather than guessed at render time: `irrational-solutions` fed to KaTeX
    renders as italic gibberish, and `\left\{x = 2, x = 3\right\}` printed as
    text is what the student was NOT supposed to read.
  */
  isLatex: boolean;
  document: ResultDoc | null;
};

/* A result is LaTeX; an error kind is not. */
function Value({ value, isLatex }: { value: string; isLatex: boolean }) {
  if (!isLatex) {
    return <span className="font-mono text-[11px] text-ink-muted">{value}</span>;
  }
  return (
    <span className="inline-block align-middle">
      <KatexMath math={value} />
    </span>
  );
}

function Case({ corpusCase, strings }: { corpusCase: CapabilityCase; strings: TreeStrings }) {
  const [outcome, setOutcome] = useState<Outcome | null>(null);
  const [pending, setPending] = useState(false);

  const run = () => {
    setPending(true);
    solve(corpusCase.latex)
      .then((document) => setOutcome(compare(corpusCase, document)))
      .catch((error: unknown) =>
        setOutcome({
          agrees: false,
          expected: corpusCase.result_latex ?? corpusCase.error ?? "",
      isLatex: !corpusCase.error,
          got: error instanceof Error ? error.message : String(error),
          document: null,
        }),
      )
      .finally(() => setPending(false));
  };

  const steps = outcome?.document ? toSteps(outcome.document) : [];
  const decimal = outcome?.document ? decimalOf(outcome.document) : null;

  return (
    <div className="rounded-[var(--radius-md)] border border-border px-4 py-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <span className="min-w-0 overflow-x-auto">
          <KatexMath math={corpusCase.latex} />
        </span>
        <span className="flex items-center gap-2">
          <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink-muted">
            {corpusCase.stage}
          </span>
          <button
            type="button"
            onClick={run}
            disabled={pending}
            className="rounded-full border border-border px-3 py-1 font-mono text-[11px] text-ink transition-colors hover:border-primary hover:text-primary"
          >
            {pending ? strings.running : strings.run}
          </button>
        </span>
      </div>

      {outcome && (
        <div className="mt-3 space-y-2 text-sm">
          <p
            className={`flex flex-wrap items-center gap-x-2 gap-y-1 ${
              outcome.agrees ? "text-primary" : "text-red-500"
            }`}
          >
            <span>{outcome.agrees ? `✓ ${strings.matches}` : `✗ ${strings.mismatch}`}</span>
            {outcome.agrees ? (
              <Value value={outcome.got} isLatex={outcome.isLatex} />
            ) : (
              <>
                <span className="font-mono text-[11px] text-ink-muted">
                  {strings.expected}:
                </span>
                <Value value={outcome.expected} isLatex={!corpusCase.error} />
                <span className="font-mono text-[11px] text-ink-muted">· {strings.got}:</span>
                <Value value={outcome.got} isLatex={outcome.isLatex} />
              </>
            )}
          </p>

          {decimal && <p className="font-mono text-[11px] text-ink-muted">≈ {decimal}</p>}

          {steps.length > 0 && (
            <ol className="space-y-1">
              {steps.map((step) => (
                <li key={step.index} className="flex flex-wrap items-baseline gap-2">
                  <span className="font-mono text-[11px] text-ink-muted">{step.index}.</span>
                  <span className="text-[13px] text-ink-muted">{step.title}</span>
                  <KatexMath math={step.after} />
                </li>
              ))}
            </ol>
          )}

          {outcome.document && <FactList facts={outcome.document.facts} />}
          {outcome.document && (
            <p className="font-mono text-[11px] text-ink-muted">
              {verificationLabel(outcome.document)}
            </p>
          )}
        </div>
      )}
    </div>
  );
}

/*
  What the corpus fixes is what gets compared: the exact result, or the error kind when the
  right answer is an error. Same comparison as engine/scripts/browser-check.mjs — if this
  ever passes something that script fails, one of the two is lying.
*/
function compare(corpusCase: CapabilityCase, document: ResultDoc): Outcome {
  if (corpusCase.error) {
    const kind = document.error?.kind ?? "—";
    return {
      agrees: kind === corpusCase.error,
      expected: corpusCase.error,
      got: kind,
      isLatex: false,
      document,
    };
  }

  const latex = document.result?.latex ?? document.error?.kind ?? "—";
  return {
    agrees: latex === corpusCase.result_latex,
    expected: corpusCase.result_latex ?? "—",
    got: latex,
    // Un fallo puede devolver un `kind` de error donde se esperaba LaTeX, y
    // entonces lo que hay en `got` no es LaTeX aunque `expected` sí lo sea.
    isLatex: document.result !== null,
    document,
  };
}

function Mark({ checked }: { checked: boolean }) {
  return (
    <span
      aria-hidden
      className={`inline-block h-3 w-3 shrink-0 rounded-[3px] border ${
        checked ? "border-primary bg-primary" : "border-border"
      }`}
    />
  );
}
